# Node.js
# Build a general Node.js project with npm and run Cypress tests.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master  # Trigger on changes to the master branch

pool:
  vmImage: ubuntu-latest  # Use the latest Ubuntu virtual machine

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'  # Install Node.js version 20.x
  displayName: 'Install Node.js'

- script: |
    npm install  # Install project dependencies
    npm run build  # Build the project
  displayName: 'npm install and build'

- script: npx cypress install  # Ensure Cypress is installed
  displayName: 'Install Cypress'

- script: npx cypress run  # Run Cypress tests
  displayName: 'Run Cypress Tests'
